### ISSUE TITLE
Arducam OV5642 camera with USB shield not working

### ISSUE THREAD

**Issue by amalhub** [ArduCAM/ArduCAM_USB_Camera_Shield#112]
Hi, 
I have purchased Arducam OV5642 camera (UC-234 Rev.B) and I'm trying to connect it to my Ubuntu 16.04 pc using the Arducam USB camera shield (UC-391 Rev.D). I have tried with both Python and Cpp but nothing works. The camera initializes but doesn't return any image data. 

Below screenshot is the Cpp error. 
![Arducam-Cpp-Error](https://user-images.githubusercontent.com/7391925/61343733-32a6e200-a892-11e9-9635-752042f63834.png)

Below screenshot is the Python error.
![Arducam-Python-error](https://user-images.githubusercontent.com/7391925/61343749-40f4fe00-a892-11e9-8583-c1cbfb2a0cea.png)

I have tried it in Windows as well but still, it doesn't work. Camera gets initialized but doesn't return any image data. I mainly need this to work in Ubuntu/Linux environment. 
Can you please help me with resolving this issue?

**Comment by glddiv** [comment]
Hi @amalhub 
Can you try this configuration file?
[OV5642_Config_File.zip](https://github.com/ArduCAM/ArduCAM_USB_Camera_Shield/files/3400370/OV5642_Config_File.zip)

**Comment by amalhub** [comment]
Hi @glddiv 
Thanks for the configuration files. I tried the configuration files but still, get the same error. :( 
Do you have any other solutions or insight what cause these error and why the device doesn't work out of the box?

**Comment by glddiv** [comment]
> Hi @glddiv
Thanks for the configuration files. I tried the configuration files but still, get the same error. :(
Do you have any other solutions or insight what cause these error and why the device doesn't work out of the box?

I am not sure what caused this error, I used the same hardware as you and it works. Can you send me the error message you printed using the USBTest program on Windows?

**Comment by amalhub** [comment]
Hi @glddiv 
I was initially testing your configs in the Linux environment with Python scripts and it gave me the same error. It looks same as the screenshots in my previous comment. However when you mention that you tested the scripts on Windows environment then I did the same later. It works in Windows environment with .cfg file. Then I tested the .json file in Linux Cpp environment and got it to work as well. For some reason, the config files are not compatible with Python. However, I'm satisfied since they are working with Linux Cpp.

**Comment by amalhub** [comment]
I have one more question. 
The default configurations in the camera are set to return 2592x1944 resolution with 8fps. 
I need the camera to work with a much lower resolution with a higher frame rate. Ex: 1280x720 resolution with 30fps.
Can you please show me how can I modify the configurations to achieve this?

**Comment by glddiv** [comment]
> For some reason, the config files are not compatible with Python. 

The Python script has a bug which has now been fixed.

**Comment by amalhub** [comment]
> > For some reason, the config files are not compatible with Python.
> 
> The Python script has a bug which has now been fixed.

Thank you for supporting to solve the initial issue. Can I please get some help on how to update the configurations as per my requirements given above?

**Comment by glddiv** [comment]
@amalhub 
If you want to modify the image resolution and frame rate, you need to modify a series of sensor registers. This is not an area I am good at. I have already submitted your question to the relevant engineer. If there is any new news, you will get a reply.

**Comment by glddiv** [comment]
Hi @amalhub 
This is a 1280x720 configuration file.
[OV5642_1280x720_Config_File.zip](https://github.com/ArduCAM/ArduCAM_USB_Camera_Shield/files/3415874/OV5642_1280x720_Config_File.zip)

**Comment by amalhub** [comment]
Hi @glddiv 
Thank you for the configurations.
Do you have any documentation on how to configure the sensor registry values? 
Are you using a standard IC or some custom made one? If I could get my hands on the datasheet or a manual on setting the registry values, it would be great for my project work.

**Comment by ArduCAM** [comment]
You can find how to read/write sensor register from the information below:
https://www.arducam.com/docs/usb-cameras/usb-camera-shield/software-sdk-and-api-for-c-c/ 
OV5642 datasheet can be found below:
www.arducam.com/downloads/modules/OV5642_V1.11.pdf

**Comment by mitchgalea** [comment]
Hi @ArduCAM 
The second link does not seem to work. When I access the pdf file I get the 404 response from your website. Could you please recheck and send me the download link?

**Comment by amalhub** [comment]
Hi @ArduCAM
The second link does not seem to work. When I access the pdf file I get the 404 response from your website. Could you please recheck and send me the download link?

**Comment by ArduCAM** [comment]
It should be https://www.arducam.com/downloads/modules/OV5642/OV5642_V1.11.pdf  
Sorry for the inconvenience.

**Comment by amalhub** [comment]
Thanks for all the support! :+1:
