### ISSUE TITLE
Connect 2 or more ArduCams to a single PC

### ISSUE THREAD

**Issue by amalhub** [ArduCAM/ArduCAM_USB_Camera_Shield#114]
Hi, 
I'm using Arducam OV5642 camera (UC-234 Rev.B) with Arducam USB camera shield (UC-391 Rev.D) to connect them into my Ubuntu 16.04 pc. When I connect multiple cameras and run the cpp script, only the last device start streaming. How can I run multiple cameras simultaneously?

**Comment by loopy83** [comment]
Hi, did you solve this problem?

**Comment by amalhub** [comment]
@loopy83 : Yes, the solution is in ticket https://github.com/ArduCAM/ArduCAM_USB_Camera_Shield/issues/116
