### ISSUE TITLE
MT9J001 USB 3.0 Shield Issues

### ISSUE THREAD

**Issue by qiankairong** [ArduCAM/ArduCAM_USB_Camera_Shield#118]
We just bought MT9J001 with USB 3.0 Shield. However, we are having issues of getting good images. I have tried on Windows 10 (using the UTest app) and for the first time I was able to get some reasonable image (first one below), but for some reason, the second time I connected the camera, I'm start to get noisy images (second one below). We bought two of these modules and I observed same on both. I tried to tune the gain and exposure, but I don't think this is related to that. I also tried this on Nvidia Jetson Nano and Tx2 board, there I couldn't get it to work. So my question is that how many of you actually using this module and do you have similar problems? You help will be greatly appreciated.

![ArduCam_01](https://user-images.githubusercontent.com/43415840/62743700-414b6980-b9f8-11e9-9dd7-c6146d477c31.JPG)
![ArduCam_02](https://user-images.githubusercontent.com/43415840/62743704-44def080-b9f8-11e9-89f2-79ca8cf305a8.JPG)

**Comment by ArduCAM** [comment]
@qiankairong Did you made it work? Can you share how you fix it?
Thanks.
