### ISSUE TITLE
About the naming of config file

### ISSUE THREAD

**Issue by jasonchenPJ** [ArduCAM/ArduCAM_USB_Camera_Shield#164]
Hi @ArduCAM 
I'm confused about this naming of config file.
Ex: IMX477_2Lane_2048x1520_RAW10_10b.cfg

What's mean the 10b? 
And is the RAW10 mean the ADC output of IMX477 ?

thanks~

**Comment by ArduCAM** [comment]
10b is the RAW10 format and outputs 10bit wide data in 16bit form as well.
