### ISSUE TITLE
MT9J001 open fail in Python demo code

### ISSUE THREAD

**Issue by masalha-alaa** [ArduCAM/ArduCAM_USB_Camera_Shield#166]
Hi,

I have an **MT9J001** sensor connected by a **USB3** cable to a **Windows PC** on  a **USB3 port**, and I'm trying to run the provided **Python** example by following the instructions on your [Readme page](https://github.com/ArduCAM/ArduCAM_USB_Camera_Shield/tree/master/Windows/Python/Streaming_demo) (using **Python 3.6, 64bit**). However, I can't find the **json** configuration file for **MT9J001**. In fact, I can't find any **json** configuration files in this repository. All I can find is **.cfg** files in the **Config** directory. I tried using `Config/USB3.0_UC-425_Rev.C+UC-547 Rev.B/MT9J001/MT9J001_MONO_12b_3664x2748_7fps.cfg` but I'm getting an error:

```
D:\ArduCAM_USB_Camera_Shield\Windows\Python\Streaming_demo>python ArduCam_Py_Demo.py "..\..\..\Config\USB3.0_UC-425_Rev.C+UC-547 Rev.B\MT9J001\MT9J001_MONO_12b_3664x2748_7fps.cfg"
color mode 0
open fail,rtn_val =  65281

D:\ArduCAM_USB_Camera_Shield\Windows\Python\Streaming_demo>
```

I also wrote a script to try **ALL** the **.cfg** files under the **Config** directory, but I got a **65281 error** in all 613 of them.

I also tried [the Windows GUI app](https://github.com/ArduCAM/ArduCAM_USB_Camera_Shield/tree/master/Windows/GUI/USBTest/x64/Release) **ArduCam USB Camera Demo**, and looks like it can't find the sensor, because the **Device** list is empty (even after pressing **scan**):
![image](https://user-images.githubusercontent.com/78589884/122675917-55f80b80-d1e4-11eb-88b2-e41e4e00abdd.png)

Can you please assist?

**Comment by tylerbishere** [comment]
Hey did you fix this problem because I am getting the same error?
