### ISSUE TITLE
Raspberry Pi + MT9J001

### ISSUE THREAD

**Issue by ryanmklee** [ArduCAM/ArduCAM_USB_Camera_Shield#24]
Hi,

I seem to be having an issue with the Raspberry Pi sometimes. Running the .py works well sometimes, but it also sometimes fails.

Here is my terminal output. 

pi@raspberrypi:~/Documents/ArduCAM_USB_Camera_Shield/RaspberryPi/Python $ sudo python MT9J001.py
device open success!
transfer task create success!
capture fail!
device close success!
Segmentation fault
pi@raspberrypi:~/Documents/ArduCAM_USB_Camera_Shield/RaspberryPi/Python $ sudo python MT9J001.py
device open success!
transfer task create success!
capture fail!
is not available
data length is not enough!
is not available
device close success!
data length is not enough!
Segmentation fault

**Comment by ArduCAM** [comment]
Please show me your hardware setup, we have different hardware version, the old version doesn't work well in RPI, only works well in PC.
