### ISSUE TITLE
Visible banding in images from MT9J001

### ISSUE THREAD

**Issue by rtb21** [ArduCAM/ArduCAM_USB_Camera_Shield#27]
Hi,

I've just purchased a MT9J001 (monochrome) camera and the ArduCAM USB Camera Shield and in general it is working, however the images I'm receiving from the camera have a couple of issues.
Firstly the images (especially in low light conditions) contain significant horizontal structure, and secondly the images also exhibit banding in the light level (the wall next to the light should be brighter than its surrounding but appears darker)
![image](https://user-images.githubusercontent.com/4306154/38055106-b1e4e8b6-32d0-11e8-9a23-61968bf811b3.png)

Thanks,
Rob

**Comment by ArduCAM** [comment]
Rob
Please try to increase the global gain register 0x0204 value like 0x80, and you can change the exposure register 0x3012 for much brighter image.
Let me know your testing result.

**Comment by ArduCAM** [comment]
Would you please reseat the ribbon cable on both end of the camera and the usb board, sometimes the cable tend to be loose. You can also send me your order number to admin@arducam.com, so if problem still exist, we can send you a replacement ASAP.
You can find the reigster reference from: www.arducam.com/downloads/modules/industrial/MT9J003_RR_A.pdf   
Let me know if you need more help.

**Comment by ArduCAM** [comment]
I still didn't get your reply, just waiting for your kind reply.

**Comment by rtb21** [comment]
Sorry for the delay, I have been away for a few nights.

The good news is that the camera now appears to be working, however I all I did was retry it again tonight, so I don't know what happened to fix the issue! Still, thanks for the quick responses and the link to the register reference.

Rob
