### ISSUE TITLE
what file is source?

### ISSUE THREAD

**Issue by coldstart01** [ArduCAM/ArduCAM_USB_Camera_Shield#28]
Hi Lee, what file/library do I find ArduCam_ fxs like ArduCam_capture, ArduCam_scan, etc:?

`
C:\marble_win_development\x64_MT9V034_vid\Debug/../src/MT9V034_demo.cpp:41: undefined reference to `ArduCam_beginCapture'
C:\marble_win_development\x64_MT9V034_vid\Debug/../src/MT9V034_demo.cpp:45: undefined reference to `ArduCam_capture'
C:\marble_win_development\x64_MT9V034_vid\Debug/../src/MT9V034_demo.cpp:49: undefined reference to `ArduCam_endCapture'
src\MT9V034_demo.o: In function `fnDisplay_Thread(void*)':
C:\marble_win_development\x64_MT9V034_vid\Debug/../src/MT9V034_demo.cpp:64: undefined reference to `ArduCam_available'
C:\marble_win_development\x64_MT9V034_vid\Debug/../src/MT9V034_demo.cpp:68: undefined reference to `ArduCam_read'
C:\marble_win_development\x64_MT9V034_vid\Debug/../src/MT9V034_demo.cpp:89: undefined reference to `cv::cvtColor(cv::_InputArray const&, cv::_OutputArray const&, int, int)'
C:\marble_win_development\x64_MT9V034_vid\Debug/../src/MT9V034_demo.cpp:94: undefined reference to `ArduCam_del'
src\MT9V034_demo.o: In function `main':
C:\marble_win_development\x64_MT9V034_vid\Debug/../src/MT9V034_demo.cpp:118: undefined reference to `ArduCam_scan'
C:\marble_win_development\x64_MT9V034_vid\Debug/../src/MT9V034_demo.cpp:131: undefined reference to `ArduCam_autoopen'
C:\marble_win_development\x64_MT9V034_vid\Debug/../src/MT9V034_demo.cpp:135: undefined reference to `ArduCam_writeReg_8_8'
C:\marble_win_development\x64_MT9V034_vid\Debug/../src/MT9V034_demo.cpp:136: undefined reference to `ArduCam_writeSensorReg'
C:\marble_win_development\x64_MT9V034_vid\Debug/../src/MT9V034_demo.cpp:137: undefined reference to `ArduCam_writeSensorReg'
C:\marble_win_development\x64_MT9V034_vid\Debug/../src/MT9V034_demo.cpp:139: undefined reference to `ArduCam_writeSensorReg'
C:\marble_win_development\x64_MT9V034_vid\Debug/../src/MT9V034_demo.cpp:191: undefined reference to `ArduCam_close'
collect2.exe: error: ld returned 1 exit status

`

Thank you

**Comment by ArduCAM** [comment]
This example is only for linux, you can't compile them on windows.

**Comment by coldstart01** [comment]
OK, that saved a lot of work - thank you.
What do you recommend for Windows compilation other than Visual Studio. I've compiled my own OpenCV binaries (MingGW w/ Eclipse). Would this be a successful compilation?

**Comment by ArduCAM** [comment]
Sorry, on Windows we only use Visual studio right now.

**Comment by coldstart01** [comment]
Thx for the reply. Sorry to bother. Will follow upOn Apr 16, 2018 8:50 PM, Lee <notifications@github.com> wrote:Sorry, on Windows we only use Visual studio right now.
