### ISSUE TITLE
Flip image in AR0134 module

### ISSUE THREAD

**Issue by frascuelillo** [ArduCAM/ArduCAM_USB_Camera_Shield#34]
I'm trying to mirror  image through the sensor registration values, according to the register reference of the AR0134 I have to modify bits 14 and 15 of register 0x3040, how can I access those bits? What number or character I should use for?

**Comment by ArduCAM** [comment]
If you are using windows GUI, you can input the 0x3040 in the reg eidt box, and write the corresponding value in the value edit box, then click wirte. You can also read the register value fisrt, and only modify wanted bits.

**Comment by frascuelillo** [comment]
Ok, I find it:

0x4000 horizontal flip
0x8000 vertical flip
0XC000 vertical and horizontal flip

**Comment by ArduCAM** [comment]
Congratulations!
