### ISSUE TITLE
AR0134 USBtest image size changing

### ISSUE THREAD

**Issue by frascuelillo** [ArduCAM/ArduCAM_USB_Camera_Shield#35]
How can I show an image of a size different than 1280x964 ?, when I enter another value no image is shown, and if I select the option to force display, the image shown is corrupt.
![image](https://user-images.githubusercontent.com/39522226/40748481-dbc9711c-6460-11e8-9a06-69ac0836b840.png)

**Comment by ArduCAM** [comment]
Actually for AR0134  there is extra 4 default lines enabled, so please input 484 in the Height edit box to match with your setting.

**Comment by frascuelillo** [comment]
Thank's, 
But I don't have success with that setting:

![image](https://user-images.githubusercontent.com/39522226/40770937-5028f34c-64bc-11e8-9dd9-f065749cb6c0.png)

**Comment by ArduCAM** [comment]
Can you send me your settings, so I can figure this out here.

**Comment by frascuelillo** [comment]
Hi lee, 
I sended you an email with my settings.
It´s preferable paste my settings in this post?

**Comment by ArduCAM** [comment]
Sorry, just sent by email to you.
