### ISSUE TITLE
Using Arducam USB Shield with Python under Windows.

### ISSUE THREAD

**Issue by frascuelillo** [ArduCAM/ArduCAM_USB_Camera_Shield#39]
It's possible to use Arducam USB shield in Python in a Windows PC?

**Comment by ArduCAM** [comment]
Sorry, we didn't have Python for Windows now, only Linux available. But we now have opencv C++ version for windows, does that help?

**Comment by frascuelillo** [comment]
Did you mean an OpenCV example? yes, it helps, even in c++ version.

**Comment by ArduCAM** [comment]
Let me know what kind of camera module you are using, then I can upload a c++ version opencv example soon. And let me know your email address as well.

**Comment by frascuelillo** [comment]
the module is AR0134, I will send you an email

**Comment by ArduCAM** [comment]
Just sent you by email.

**Comment by frascuelillo** [comment]
Thank´s Lee, 
I was feeling more comfortable in Python, but it's a great oportunity to learning C++. 
The example you send me work's fine.
