### ISSUE TITLE
How to use python script without root/sudo?

### ISSUE THREAD

**Issue by skypanther** [ArduCAM/ArduCAM_USB_Camera_Shield#54]
How can I access the camera from python without requiring root/sudo?

**Comment by ehong-tl** [comment]
Hi @skypanther ,

If your are using USB 2.0 shield,
try copy arducam.rules in ROS/arducam_usb2_ros/scripts folder to /etc/udev/rules.d/,
then 'sudo service udev reload' and 'sudo service udev restart'.

Reconnecting your USB shield, then you should be able to run python script without root/sudo.

**Comment by skypanther** [comment]
@ehong-tl Thank you! That works perfectly.
