### ISSUE TITLE
DeBayering potentially not working MT9J001

### ISSUE THREAD

**Issue by nifunk** [ArduCAM/ArduCAM_USB_Camera_Shield#58]
Dear all,

I am working with the MT9J001 monochrome sensor and I have a problem. Whenever I take a shot with the camera and zoom in to a maximum extent I see this kind of checkerboard pattern (as shown in the attached file). I am wondering whether you think that this is a problem with the hardware or that in the software part just the de-bayering does not work (bayer grid according to: http://www.arducam.com/downloads/modules/industrial/1Inch2.3_10_Megapixel_MT9J001_CMOS_Camera_Module_DS.pdf) 
Also is anyone else of You encountering those problems?

All the best,

Niklas
![max_zoom_own_pic](https://user-images.githubusercontent.com/22931722/46017046-dabaa700-c0d6-11e8-8cd0-15faedaeb907.JPG)

**Comment by nifunk** [comment]
Okay thanks a lot!

**Comment by ArduCAM** [comment]
@nifunk  Does that help?

**Comment by nifunk** [comment]
Yes it perfectly resolved the issue, thanks a lot!
