### ISSUE TITLE
MT9V022 in NIR or IR range

### ISSUE THREAD

**Issue by coldstart01** [ArduCAM/ArduCAM_USB_Camera_Shield#73]
I am trying to find the proper lens configuration to use MT9V022 in IR range. Have removed the IR cut. Have applied a pass-through filter from ebay...the resulting frame is still flooded with daylight. Using the MT9V022 is otherwise good but need NIR or IR specificity, and its not happening.

**Comment by ArduCAM** [comment]
Can you show me some picture for your problem, so I can see what happened.

**Comment by coldstart01** [comment]
The following 2 photos are based on Logitech camera for example only using the colored glass filter 👍 
12mm Filter Lens against 400-750nm / Pass 808-1064nm IR Laser Module
[filter link](https://www.ebay.com/itm/2pcs-12mm-Filter-Lens-against-400-750nm-Pass-808-1064nm-IR-Laser-Module/132119382959?_trkparms=aid%3D111001%26algo%3DREC.SEED%26ao%3D1%26asc%3D20160908105057%26meid%3D7839912ee7df4877a882ddf7106bf99b%26pid%3D100675%26rk%3D3%26rkt%3D15%26sd%3D222788628335%26itm%3D132119382959&_trksid=p2481888.c100675.m4236&_trkparms=pageci%3Aa3f7e725-d615-11e8-9329-74dbd180beab%7Cparentrq%3A9c8ef5ff1660ac3c0977cab9fff4dca9%7Ciid%3A1)
logitech + filter
![ir logitech](https://user-images.githubusercontent.com/31634183/47308330-46713080-d5ff-11e8-9d87-57171017d950.jpg)
logitech, no filter
![logitech no filter](https://user-images.githubusercontent.com/31634183/47308350-57ba3d00-d5ff-11e8-8ebd-4d6505e7bd73.jpg)
arducam+filter -**NIR filter (glass chip removed)
![filter arducam - ir cut](https://user-images.githubusercontent.com/31634183/47308789-9f8d9400-d600-11e8-86b1-48ecc076dc7a.jpg)
**
Arducam no filter no ir cutr
![arducam no filter no nir cut](https://user-images.githubusercontent.com/31634183/47309001-42dea900-d601-11e8-9d2d-1dc47577768a.jpg)

**Comment by coldstart01** [comment]
Here is another example. LEDs are IR
Logitech, nice isolation
![ir led and logitech](https://user-images.githubusercontent.com/31634183/47309183-c4ced200-d601-11e8-90e0-837e4e99b7d7.jpg)

Arducam MT9V022 not adequately filtered.
![ir led and arducam](https://user-images.githubusercontent.com/31634183/47309264-f0ea5300-d601-11e8-96cc-795afcca91c8.jpg)

Is the colored glass a problem in the filter?
How do I filter then using monochrome camera? Don't want to change; the global shutter is awesome.

**Comment by coldstart01** [comment]
Should the NIR Cut filter be  put back in the Arducam MT9V022?

**Comment by frascuelillo** [comment]
Are you tried to reduce exposure?, the lights you marked red seems to be a ghost reflected image by the objetive or filter optics surface.

**Comment by frascuelillo** [comment]
Sorry, I´m working with AR0134 sensor, don´t know what are the correct register for MTV9022, maybe you could try with the sensor documentation:  https://www.onsemi.com/pub/Collateral/MT9V022-D.PDF

**Comment by coldstart01** [comment]
Hi Lee, could use some help here:
1. is the problem over-exposure
2. how to change exposure time in the MT9V022

**Comment by coldstart01** [comment]
Hi Lee, this might make your end easier. The c++ Visual Studio project you guys provided is working out pretty well. It also contains the settings file ArduCamCfg.json. Maybe the exposure time can be altered in this file easily?

**Comment by ArduCAM** [comment]
The 0xAF bit[1:0] is used to control if you enable the AEC/AGC, you can try to enable these bits to see if it helps to prevent the over exposure issue.
Another way is to diasble the AEC/AGC and control the exposure by the 0x0B Coarse Shutter width.

**Comment by coldstart01** [comment]
> Another way is to diasble the AEC/AGC and control the exposure by the 0x0B Coarse Shutter width.
 Ok, setting 0xAF bit = 1, and using the filter sets up the ir isolation nicely, except still getting blooming.

To disable the AEC/AGC do I set 0xAF to 0?
If I want to set the Coarse Shutter width do I use register 11 (decimal) or 0x0B(decimal) and write a vlue i.e. 3, 32, or 64?

**Comment by coldstart01** [comment]
I think I have a handle on this. To set the exposure time manually the Automatic Exposure Control or AEC has to be disabled (AEC->R0xAF[0], 0) which then defaults to the value stored in R0x0B for exposure time.
Ok, I get it but I need your help in understanding the number I need for R0x0B (aka register 11). Can you give me a more personalized way of calculating this than the .pdf?

Thank you

**Comment by coldstart01** [comment]
I haven't heard from you, so the update is this: exiting the problems. I was using 0xAF incorrectly. The PDF datasheet stated that to identify Automatic Exposure Control use 0xAF[0], value1 and for Automatic Gain Control use 0xAF[1], value 1. If the value for the AEC is 0 it gets the exposure value from register 11. To use manual exposure register 11 AEC must be diasbled (0x0).  You may want to let the user know this and save the frustration. Also is this correct notation: 0xAF[0]. It seems the USBTest software doesn't support this.

Anyway, the MTV9022 is filtering IR well even without a filter.

**Final requests for this problem set:**
Can you please give me an example snippet c++ to set register and value?
Can you please tell me how to pass [ ] when using AEC/AGC?
Finally, camera reset.

**Comment by coldstart01** [comment]
Hi Lee, I haven't heard from you in a while. Can you just tell me how to adjust 0xAF and register 11 from within the c++ code. I only have this as a guide (below). Do I need to add a property or use an existing one?

typedef struct  
{
	Uint32			u32CameraType;			// Camera Type
	Uint16			u16Vid;					// Vendor ID for USB
	
	Uint32			u32Width;				// Image Width
	Uint32			u32Height;				// Image Height
	
	Uint32			u32Size;

	Uint8			u8PixelBytes;
	Uint8			u8PixelBits;

	format_mode		emImageFmtMode;			// image format mode 

	i2c_mode		emI2cMode;
	Uint32			u32I2cAddr;

	Uint32			u32TransLvl;
}ArduCamCfg;

**Comment by coldstart01** [comment]
Not as complicated 👍 

use ArduCam_writeSensorReg(handle, reg address, value) in main before the thread of course
