### ISSUE TITLE
Error when capturing with demo code for python ubuntu 18.04

### ISSUE THREAD

**Issue by amchagas** [ArduCAM/ArduCAM_USB_Camera_Shield#78]
now that I'm able to run the example code, I get the following error:

('Error capture image, rtn_val = ', 65318)

Any ideas or suggestions on what this might be?

thanks!

**Comment by UCTRONICS** [comment]
@amchagas 
Don't worry and our engineer will help you solve the problem.
Does it keep going wrong or occasionally go wrong? Can you see any images?
Please attach me some pictures for your error messages.

**Comment by amchagas** [comment]
Hi, thanks for the reply,
here is a screenshot of the message (note that I tried running the python script as regular user and as su). 

Also I get the error all the time, and can't see any images.

![screenshot from 2018-10-26 08-12-23](https://user-images.githubusercontent.com/3624486/47550402-01971380-d8f7-11e8-90ca-14bdfed0f60a.png)

**Comment by UCTRONICS** [comment]
@amchagas 
('open fail,rtn_val = ', 65281) means can't find the USB camera, you can run the 'lsusb' command to check if the camera connects normally. if it connects normally, you will see the ID 52cb:52cb or ID 04b4:03f1.
What's more, in order to solve your problem quickly, please tell me the UC number of your bottom board.

**Comment by amchagas** [comment]
Hey,

So lsusb gives me 52cb:52cb and the board I have is UC-391 rev.b

Thanks!

**Comment by UCTRONICS** [comment]
@amchagas 
Does it work normally now? If not, please add sudo to enable superuser permissions.

**Comment by amchagas** [comment]
no, unfortunately not... 
I'm adding sudo, but this is what I get:
![screenshot from 2018-10-26 10-43-42](https://user-images.githubusercontent.com/3624486/47558929-28137980-d90c-11e8-9dbf-9e47a317ed5c.png)

**Comment by amchagas** [comment]
One question that might be silly, is the current code compatible with all arducam boards? (v1, v2 etc)

**Comment by UCTRONICS** [comment]
@amchagas 
Yes, this code is compatible with all of the Arducam boards.
Maybe the camera has not connected normally.

**Comment by amchagas** [comment]
Hum. You mean the cable from the camera to the arducam board?

**Comment by UCTRONICS** [comment]
@amchagas 
Yes, If reconnect it and still not work normally, you can try it on windows platform.
For the detail operations, please refer to the link https://github.com/ArduCAM/ArduCAM_USB_Camera_Shield/tree/master/Windows/GUI/USBTest

**Comment by amchagas** [comment]
Great, so changing the cable made everything work! Thanks for the support!

Also the cable was flipped on the camera side, (the way it came in the box.
Just a heads up, so that other customers don't have the same problem.. )

**Comment by UCTRONICS** [comment]
@amchagas 
Great to hear you have solved your problem. 
Thanks for your advice.
