### ISSUE TITLE
Error in Capture Image on Raspberry Pi

### ISSUE THREAD

**Issue by GhostSystemV2** [ArduCAM/ArduCAM_USB_Camera_Shield#96]
Hi!
I'm having problems with the AR0134+USB3.0 Rev.C shield, when i run the Streaming_demo in a Raspberry Pi, some frames are corrupted or the terminal says "Error capture image. rtn_val =" 6531L, and i can't exit the capturing process so i have to kill the script.

In windows the camera works without problems.

![imagen](https://user-images.githubusercontent.com/13134854/55904913-8a98c300-5b96-11e9-8a34-39a666d78c74.png)

**Comment by glddiv** [comment]
@GhostSystemV2 
Try to reduce the value of the 0x3030 register.
![2019-04-11 15-52](https://user-images.githubusercontent.com/24386338/55940211-3bc05b80-5c72-11e9-89b6-c39f58889763.png)

**Comment by GhostSystemV2** [comment]
Thanks! i have reduced the value, but it looks that it has also a relation with the Frecuency of the input, in the datasheet it talks about the PLL multiplier, but why, it is defined in the register_parameter_dev_3 ?

**Comment by glddiv** [comment]
@GhostSystemV2 
The 0x3030 register has a default value. On USB 3.0 we want to get faster and we need to increase its value.
![2019-04-16 10-28-53屏幕截图](https://user-images.githubusercontent.com/24386338/56177836-a7b81080-6032-11e9-9d4f-6ac08cc121b2.png)

**Comment by GhostSystemV2** [comment]
Okay, perfect, thanks for the information.
